### ISSUE TITLE
ATTENTION kubeclient repo will be moving to the ManageIQ org soon

### ISSUE THREAD

**Issue by abonas** [ManageIQ/kubeclient#542] opened 2022-02-23 08:18 UTC
Dear community members,
This repo will be moving to the ManageIQ org on Github in the near future.
Thanks everyone for your contributions and usage of this repo so far!

cc @cben @grosser @Fryguy @agrare

**Comment by cben** [comment] 2022-03-01 22:23
# :heavy_check_mark: It moved last Thursday.

To give some context: this was a result of some discussions to ensure maintainer continuity for this gem.  
I'm still here but my spare time over last 2 years proved insufficient.  I hope to close the current gap of lots of unreleased changes "soon-ish", but after a few months I might gradually become less active...

Having it under an organization makes adding more people easier.  At least @agrare has agreed to join as maintainer.  The manageiq project relies on kubeclient and has interest in it remaining active and healthy.  The choice of manageiq org was driven by convenience to manage the repo, but kubeclient remains "neutral" as it always was intended.

**On rubygems nothing moved, it'll still be released as [`kubeclient`](https://rubygems.org/gems/kubeclient).**

Both browser and git access redirect from abonas/kubelient to ManageIQ/kubeclient transparently, but for people with local checkouts it's recommended to update the remote:
```
git remote set-url origin https://github.com/ManageIQ/kubeclient.git
git remote set-url --push origin git@github.com:ManageIQ/kubeclient.git
```

**Closed** 2022-03-01 22:34 UTC
